### ISSUE TITLE
Claudia doesn't work

### ISSUE THREAD

**Issue by fangyi-zhou** [ycmjason/ic-claudia#1]
No result shown.

Error indicated:

XMLHttpRequest cannot load https://www.doc.ic.ac.uk/~cmy14/claudia/press3.php. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.doc.ic.ac.uk' is therefore not allowed access.

**Comment by ycmjason** [comment]
You need to access to claudia through https.

This is weird tho because I cannot recreate your error. Can you show me the steps you did in order to create this error? Also can you note your browser too?

**Comment by ycmjason** [comment]
Anyways, I have added a line of javascript for redirecting http->https. Hopefully this solves the problem.

[see the commit](https://github.com/ycmjason/ic-claudia/commit/dd6bb5fc0b4564a00315c72b51a945f330a3ba73)

Thank you for reporting.

**Comment by fangyi-zhou** [comment]
The problem arose from not using HTTPS (from clicking the link in the email), and is fixed now. Thank you.
